[build]
  # The directory where the app source code lives
  base = "app"
  
  # The command to build the app (relative to the base directory)
  command = "npm install && npm run build"
  
  # The directory that Netlify will serve (relative to the base directory)
  publish = "dist"

[[redirects]]
  # This ensures that React Router works correctly on refresh
  from = "/*"
  to = "/index.html"
  status = 200
